/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yzohbugsywyidfxbadwo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6b2hidWdzeXd5aWRmeGJhZHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNDE1MzAsImV4cCI6MjA3ODkxNzUzMH0.uu8V2iZHp_vkqbOtMBSj3s8OjJ-0__sHT-0bFPcjrQ4"